<?php

class Ajax_Widget extends WP_Widget {
    public function __construct()
    {
        $widget_options = array(
            'classname'   => 'ajax_widget',
            'description' => __( 'Ajax Widget' )
        );
        parent::__construct( 'ajax_widget', __( 'Ajax Widget' ), $widget_options );
    }

    public function widget($args, $instance) {
        ?>
        <form action="" id="get_post_title_form">
            <input type="text" name="post_title" placeholder="Enter Title"/>
            <input type="date" name="post_date" placeholder="enter date" required/>
            <button class="button">Get Title</button>
            <input type="hidden" name="action" value="getposttitle">
        </form>
        <?php

    }

    public function form($instance)
    {
        return parent::form($instance); // TODO: Change the autogenerated stub
    }

    public function update($new_instance, $old_instance)
    {
        return parent::update($new_instance, $old_instance); // TODO: Change the autogenerated stub
    }
}

function ajax_register_widget() {
    register_widget( 'Ajax_Widget' );
}
add_action( 'widgets_init', 'ajax_register_widget' );